Changes in file payload/bin/find_exec_tool_is_from_pkg:  Unknown Changes

diff --git a/payload/bin/find_exec_tool_is_from_pkg b/payload/bin/find_exec_tool_is_from_pkg
--- a/payload/bin/find_exec_tool_is_from_pkg
+++ b/payload/bin/find_exec_tool_is_from_pkg
@@ -60,19 +60,111 @@
 #    even if the above stated remedy fails of its essential purpose.
 ################################################################################
 
+# Usage Summary:
+#    find_exec_tool_is_from_pkg FILE
+#
+# Exit Code Summary:
+# The script uses the EXIT_CODE variable to track exit conditions:
+# -   0: Successful execution.
+# -   1: General failure.
+# - 126: Script already in progress or command not executable.
+# - 129: Received SIGHUP signal.
+# - 130: Received SIGINT signal (Ctrl+C).
+# - 131: Received SIGQUIT signal.
+# - 137: Received SIGABRT signal.
+# - 143: Received SIGTERM signal.
+
+# Try to safely setup and fail fast if unable.
+ulimit -t 60
+# setting the path may break brain-dead CI that uses crazy paths
+# PATH="/bin:/sbin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
 THE_FILE="${@:1:$#}"
-hash -p /usr/sbin/pkgutil pkgutil
-hash grep
-hash cut
 umask 137
+
+# force utf-8 for checking in script
+export LC_CTYPE="${LC_CTYPE:-en_US.UTF-8}"
+
+# Function to check if a command exists.
+
+# USAGE:
+#	~$ check_command CMD
+# Arguments:
+# CMD (Required) -- Name of the command to check
+# Results:
+#	exits 64 -- missing required argument
+#	exits 126 -- check complete and has failed, can not find given command.
+#	returns successful -- check complete and command found to be executable.
+function check_command() {
+	test -z "$1" && { printf "%s\n" "Error: command name is required to check for existence." >&2 ; exit 64 ; } ;
+	local cmd="$1" ;
+	test -x "$(command -v ${cmd})" || { printf "%s\n" "Error: Required command '$cmd' is not found." >&2 ; exit 126 ; } ;
+}  # end check_command()
+# propagate/export function to sub-shells
+export -f check_command
+
+# Check required commands
+check_command grep ;
+check_command cut ;
+hash -p /usr/sbin/pkgutil pkgutil || exit 127 ;
+check_command pkgutil ;
+# CAVEAT: NON-CEP-5 locking is OK (Apple systems should have a shlock builtin)
+test -x ./.github/tool_shlock_helper.sh && hash -p ./.github/tool_shlock_helper.sh shlock || : ;
+check_command shlock ;
+
+# set remaining variables
+LOCK_FILE="${TMPDIR:-/tmp}/org.ymmv.find-tool-pkg-shell"
+
+# Set default exitcode to failure until sure we won't need to abort
+EXIT_CODE=1
+
+# end of bootstraping, use functions below this point
+
+# Function to check if a command exists.
+
+# USAGE:
+#	~$ cleanup
+# Arguments:
+#	N/A
+# Results:
+#	returns -- once cleanup has been done on a best-effort case.
+function _cleanup() {
+	unset THE_FILE || true ;
+	return
+	rm -f ${LOCK_FILE} 2>/dev/null || : ; wait ;
+	# unset when done
+	unset LOCK_FILE 2>/dev/null || : ;
+	hash -d find_exec_tool_is_from_pkg 2>/dev/null || : ;
+	hash -d shlock 2>/dev/null || : ;
+}
+
+function handle_signals() {
+	if [[ ( $(shlock -f ${LOCK_FILE} -p $$ ) -eq 0 ) ]] ; then
+		EXIT_CODE=0
+		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit 129 ;' SIGHUP || EXIT_CODE=129
+		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit 143 ;' SIGTERM || EXIT_CODE=143
+		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit 131 ;' SIGQUIT || EXIT_CODE=131
+		# SC2173 - https://github.com/koalaman/shellcheck/wiki/SC2173
+		#trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit 1 ;' SIGSTOP || EXIT_CODE=7
+		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit 130 ;' SIGINT || EXIT_CODE=130
+		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit 137 ;' SIGABRT || EXIT_CODE=137
+		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit ${EXIT_CODE} ;' EXIT || EXIT_CODE=1
+	else
+		# shellcheck disable=SC2046
+		printf "\t%s\n" "Check Setup Scripts Tests Coverage already in progress by "$(head "${LOCK_FILE}") >&2 ;
+		exit 126 ;
+	fi
+}
+
+handle_signals
 
 if [[ ( -e "${THE_FILE}" ) ]] ; then
 	TEMP_APP_SOURCE=$(pkgutil --file-info "${THE_FILE}" 2>/dev/null | grep -F "pkgid:" 2>/dev/null | cut -d: -f 2 2>/dev/null )
-	if [[ ( -n "$TEMP_APP_SOURCE" ) ]] ; then true ; else false ; fi
-	exit $? ;
+	if [[ ( -n "$TEMP_APP_SOURCE" ) ]] ; then true ; else false ; fi ; EXIT_CODE=$? ;
 else
-	echo "$0: No such path: \'$THE_FILE\'" 1>&2 ;
-	false ;
-	exit $? ;
+	printf "%s\n" "$0: No such path: \'$THE_FILE\'" 1>&2 ;
+	false ; EXIT_CODE=$? ;
 fi
-exit 255 ;
+
+cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || : ; wait ;
+
+exit ${EXIT_CODE:-70} ;
