[PATCH] Improved code quality more
Changes in file payload/bin/find_exec_tool_is_from_Apple_pkg:
 * minor changes

Changes in file payload/bin/find_exec_tool_is_from_pkg:
 * minor changes

Changes in file payload/bin/git-filter-dedup:
 * minor changes

Changes in file payload/bin/git-tool-auto-pull:
 * minor changes

Changes in file payload/bin/grepCIDR:
 * minor changes

Changes in file payload/bin/grepdns:
 * minor changes

Changes in file payload/bin/grepip:
 * minor changes

Changes in file payload/bin/lsmap:
 * improved handling for archives

diff --git a/payload/bin/git-filter-dedup b/payload/bin/git-filter-dedup
--- a/payload/bin/git-filter-dedup
+++ b/payload/bin/git-filter-dedup
@@ -140,7 +140,7 @@ else
 		if [[ ( $(file -b --mime "${_GIT_TOOL_BUFFER}" | grep -cioF "text/plain" ) -lt 1 ) ]] ; then
 			IS_SMUDGE_MODE=0 ;
 			EXIT_CODE=64 ;
-			printf "%s\n" "Error: Non-text data can not be filtered!" 1>&2 ; exit 2 ;;
+			printf "%s\n" "Error: Non-text data can not be filtered!" 1>&2 ; exit 2 ;
 		fi
 		# else the file is ok to try and smudge
 	fi
