[PATCH] Part 3 - align scripts with CEP-8 Changes in file payload/bin/git-filter-data:  - aligned exit codes
Changes in file payload/bin/git-filter-dedup:
 - aligned exit codes

diff --git a/payload/bin/git-filter-data b/payload/bin/git-filter-data
--- a/payload/bin/git-filter-data
+++ b/payload/bin/git-filter-data
@@ -7,7 +7,7 @@
 #    EFFORT IS WITH YOU.
 #
 # B. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THIS SHELL SCRIPT
-#    AND SERVICES ARE PROVIDED "AS IS" AND “AS AVAILABLE”, WITH ALL FAULTS AND
+#    AND SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE", WITH ALL FAULTS AND
 #    WITHOUT WARRANTY OF ANY KIND, AND THE AUTHOR OF THIS SHELL SCRIPT'S LICENSORS
 #    (COLLECTIVELY REFERRED TO AS "THE AUTHOR" FOR THE PURPOSES OF THIS DISCLAIMER)
 #    HEREBY DISCLAIM ALL WARRANTIES AND CONDITIONS WITH RESPECT TO THIS SHELL SCRIPT
@@ -64,62 +64,71 @@ declare -ir MINPARAMS=0;
 declare -i IS_SMUDGE_MODE=0;
 declare -i IS_CLEAN_MODE=0;
 declare -i IS_VERBOSE_MODE=0;
-declare -ir MYVERSION=20220219;
+declare -ir MYVERSION=20241101;
+declare GIT_FILTER_TOOL_DATA_SKIP=`git config --bool --default false --get 'filter.data.skip'`;
+# Can force skip this filter by setting the git-config option 'filter.data.skip' like so:
+# git config --bool --set 'filter.data.skip' true
 
-if [[ $# -gt "$MINPARAMS" ]] ; then
-while [ $# -gt $MINPARAMS ]; do    # Until you run out of parameters . . .
-
-case "$1" in
-  -s|--in|--smudge) IS_SMUDGE_MODE=1 ;;
-  -c|--out|--clean) IS_CLEAN_MODE=1 ;;
-  -v|--verbose) IS_VERBOSE_MODE=1 ;;
-  -V|--version) echo "${MYVERSION}" ; exit 0 ;;
-  -*) echo "Error: \"${1}\" Argument Unrecognized!" 1>&2 ; exit 2 ;;
-esac
-shift       # Check next set of parameters.
-done
-fi
-
-# before doing anything buff the data
-
-_GIT_TOOL_BUFFER="${TMPDIR}"/"git_tool_buffer_${MYVERSION}_$$_${RANDOM}.tmp" ;
-LOCK_FILE="${TMPDIR:-/tmp}/git_tool_script_lock" ;
-EXIT_CODE=0
+_GIT_TOOL_BUFFER="${TMPDIR}"/"git_tool_buffer_${MYVERSION}_${RANDOM}_${RANDOM}_${RANDOM}.tmp" ;
+LOCK_FILE="${TMPDIR:-/tmp}/org.git.tool-script.lock" ;
+EXIT_CODE=1
 
 function cleanup() {
-	unset IS_SMUDGE_MODE || true ;
-	unset IS_CLEAN_MODE || true ;
-	unset IS_VERBOSE_MODE || true ;
-	rm -f "${_GIT_TOOL_BUFFER}" 2>/dev/null || true ;
-	rm -f "${LOCK_FILE}" 2>/dev/null || true ; wait ;
-	unset _GIT_TOOL_BUFFER || true ;
-	unset LOCK_FILE || true ;
+	unset IS_SMUDGE_MODE || : ;
+	unset IS_CLEAN_MODE || : ;
+	unset IS_VERBOSE_MODE || : ;
+	unset GIT_FILTER_TOOL_DATA_SKIP || : ;
+	rm -f "${_GIT_TOOL_BUFFER}" 2>/dev/null || : ;
+	rm -f "${LOCK_FILE}" 2>/dev/null || : ; wait ;
+	unset _GIT_TOOL_BUFFER || : ;
+	unset LOCK_FILE || : ;
 	return
 }
 
 export -f cleanup ;
 
-if [[ ( $(shlock -f ${LOCK_FILE} -p $$ ) -eq 0 ) ]] ; then
-	trap 'cleanup || true ;' SIGHUP || EXIT_CODE=3
-	trap 'cleanup || true ;' SIGTERM || EXIT_CODE=4
-	trap 'cleanup || true ;' SIGQUIT || EXIT_CODE=5
-	trap 'cleanup || true ;' SIGSTOP || EXIT_CODE=7
-	trap 'cleanup || true ;' SIGINT || EXIT_CODE=8
-	trap 'cleanup || true ;' SIGABRT || EXIT_CODE=9
-	trap 'cleanup || true ; exit ${EXIT_CODE:-255} ;' EXIT || EXIT_CODE=1
-else
-	echo Test already in progress by `head ${LOCK_FILE}` ;
-	false ;
-	exit 255 ;
+function handle_signals() {
+	if [[ ( $(shlock -f ${LOCK_FILE} -p $$ ) -eq 0 ) ]] ; then
+		EXIT_CODE=0
+		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit 129 ;' SIGHUP || EXIT_CODE=129
+		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit 143 ;' SIGTERM || EXIT_CODE=143
+		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit 131 ;' SIGQUIT || EXIT_CODE=131
+		# SC2173 - https://github.com/koalaman/shellcheck/wiki/SC2173
+		#trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit 1 ;' SIGSTOP || EXIT_CODE=7
+		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit 130 ;' SIGINT || EXIT_CODE=130
+		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit 137 ;' SIGABRT || EXIT_CODE=137
+		trap 'cleanup 2>/dev/null || rm -f ${LOCK_FILE} 2>/dev/null || true ; wait ; exit ${EXIT_CODE} ;' EXIT || EXIT_CODE=1
+	else
+		# shellcheck disable=SC2046
+		printf "\t%s\n" "Git-Filter-Data Script already in progress by "$(head "${LOCK_FILE}") >&2 ;
+		exit 126 ;
+	fi
+}
+
+handle_signals
+
+if [[ $# -gt "$MINPARAMS" ]] ; then
+while [ $# -gt $MINPARAMS ]; do  # Until you run out of parameters . . .
+
+case "$1" in
+  -s|--in|--smudge) IS_SMUDGE_MODE=1 ;;
+  -c|--out|--clean) IS_CLEAN_MODE=1 ;;
+  -v|--verbose) IS_VERBOSE_MODE=1 ;;
+  -V|--version) printf "%s\n" "${MYVERSION}" ; exit 0 ;;
+  -*) printf "%s\n" "Error: \"${1}\" Argument Unrecognized!" 1>&2 ; exit 2 ;;
+esac
+shift  # Check next set of parameters.
+done
 fi
 
-cat </dev/stdin >"${_GIT_TOOL_BUFFER}" 2>/dev/null ; wait ;
+# before doing anything buff the data
+{ cat </dev/stdin >"${_GIT_TOOL_BUFFER}" 2>/dev/null || EXIT_CODE=65 } ; wait ;
 
 if [[ ( $IS_SMUDGE_MODE -eq 1 ) ]]; then
 	# first check if we need to smudge at all
 	if [[ ( $(file -b --mime "${_GIT_TOOL_BUFFER}" | grep -coF "text/plain" ) -lt 1 ) ]] ; then
 		IS_SMUDGE_MODE=0 ;
-		EXIT_CODE=5 ;
+		EXIT_CODE=64 ;
 	fi
 	# else the file is ok to try and smudge
 fi
@@ -128,15 +137,17 @@ if [[ ( $IS_CLEAN_MODE -eq 1 ) ]]; then
 	# first check if we need to clean at all
 	if [[ ( $(file -b --mime "${_GIT_TOOL_BUFFER}" | grep -coF "text/plain" ) -ge 1 ) ]] ; then
 		IS_CLEAN_MODE=0 ;
-		EXIT_CODE=5 ;
+		EXIT_CODE=64 ;
 	fi
 	# else the file is not plain text and is ok to try and clean
 fi
 
 if [[ ( $IS_CLEAN_MODE -eq 1 ) ]] ; then
 	cat <"${_GIT_TOOL_BUFFER}" | xxd -ps ;
+	EXIT_CODE=$? ;
 elif [[ ( $IS_SMUDGE_MODE -eq 1 ) ]] ; then
 	cat <"${_GIT_TOOL_BUFFER}" | xxd -ps -r ;
+	EXIT_CODE=$? ;
 else
 	cat <"${_GIT_TOOL_BUFFER}" ;
 fi
@@ -144,4 +155,4 @@ fi
 #GIT_FILTER_TOOL_DATA_OPT=`git config --bool --default true --get 'filter.data.option'`
 # always clean up
 cleanup || true ; wait ;
-exit ${EXIT_CODE} || exit 255 ;
+exit ${EXIT_CODE:-1};
