[FEATURE] git filter tool for bianary data types

diff --git a/payload/bin/git-difftool-archive b/payload/bin/git-difftool-archive
--- a/payload/bin/git-difftool-archive
+++ b/payload/bin/git-difftool-archive
@@ -62,14 +62,49 @@
 
 umask 137
 
+if [[ ( ${#} -gt 2 ) ]] ; then
+#expects the following arguments path old-file old-hex old-mode new-file new-hex new-mode
+	export _GIT_DIFF_TOOL_ARCH_PATH="${1:-'/dev/null'}"
+	export _GIT_DIFF_TOOL_OUR_PATH="${2:-'/dev/null'}"
+	export _GIT_DIFF_TOOL_OUR_MODE="${4:-'100755'}"
+	export _GIT_DIFF_TOOL_THIER_PATH="${5:-'/dev/null'}"
+	export _GIT_DIFF_TOOL_THIER_MODE="${7:-'000000'}"
+	export _GIT_DIFF_TOOL_OUR_SHA="${3:-'4b825dc642cb6eb9a060e54bf8d69288fbee4904'}"
+	export _GIT_DIFF_TOOL_THIER_SHA="${6:-'1000000000000000000000000000000000000000'}"
+	#echo "Path: ${_GIT_DIFF_TOOL_ARCH_PATH:-'Missing'}"
+	#echo "Old-file: ${_GIT_DIFF_TOOL_OUR_PATH}"
+	#echo "Old-hex: ${_GIT_DIFF_TOOL_OUR_SHA}"
+	#echo "Old-mode: ${_GIT_DIFF_TOOL_OUR_MODE}"
+	#echo "New-file: ${_GIT_DIFF_TOOL_THIER_PATH}"
+	#echo "New-hex: ${_GIT_DIFF_TOOL_THIER_SHA}"
+	#echo ""
+	echo "${_GIT_DIFF_TOOL_THIER_SHA}"
+	#echo "diff --git a/${_GIT_DIFF_TOOL_ARCH_PATH} b/${_GIT_DIFF_TOOL_THIER_PATH}" | tr -s '/' ;
+#if git rev-parse --verify ${_GIT_DIFF_TOOL_OUR_SHA} >/dev/null 2>&1
+#then
+#    _GIT_DIFF_TOOL_DIFF_TYPE="N" ;
+#else
+#    _GIT_DIFF_TOOL_DIFF_TYPE="M" ;
+#fi
+
+	#echo "New-mode: ${_GIT_DIFF_TOOL_THIER_MODE}"
+else
+	echo "${0}: bad args: ${#} - '${@}'" 1>&2 && exit 125 ;
+fi
+
+#LOCAL="${LOCAL:-${_GIT_DIFF_TOOL_OUR_PATH}}"
+#REMOTE="${REMOTE:-${_GIT_DIFF_TOOL_THIER_PATH}}"
+#MERGE="${_GIT_DIFF_TOOL_ARCH_PATH}"
+
+
 GIT_DIFF_TOOL_FSCK_ALL=`git config --bool --default true --get 'diff.archive.fsck'`
 GIT_DIFF_TOOL_FSCK_TAR=`git config --bool --default ${GIT_DIFF_TOOL_FSCK_ALL} --get 'diff.archive.tar.fsck'`
 
 if [[ !( $GIT_DIFF_TOOL_FSCK_TAR ) ]] ; then
-#echo "${LOCAL}"
-tar -tf ${LOCAL} >/dev/null || exit 125 ;
-#echo "${REMOTE}"
-tar -tf ${REMOTE} >/dev/null || exit 125 ;
+#echo "${_GIT_DIFF_TOOL_OUR_PATH}"
+tar -tf ${_GIT_DIFF_TOOL_OUR_PATH} >/dev/null || exit 125 ;
+#echo "${_GIT_DIFF_TOOL_THIER_PATH}"
+tar -tf ${_GIT_DIFF_TOOL_THIER_PATH} >/dev/null || exit 125 ;
 fi
 
 declare -i GIT_DIFF_TOOL_FNAMES_BUFFER_LEN=`git config --int --default 512 --get 'diff.archive.filename-buffer-len'`
@@ -77,7 +112,7 @@ declare -i GIT_DIFF_TOOL_CONTEXT=`git config --int --default 3 --get 'diff.conte
 
 # caveat: can not be overridden with git_config_count like stuff...
 # colors (only old,new,meta,func, and context are supported)
-if [[ ( $(git config --get-colorbool color.diff `test -t 0` ) ) ]] ; then
+if [[ ( $(git config --get-colorbool color.diff `test -t 1` ) -eq 1 ) ]] ; then
 gitdiffoldcolor=$(git config --get-color color.diff.old "default") ;
 gitdiffnewcolor=$(git config --get-color color.diff.new "default") ;
 gitdiffmetacolor=$(git config --get-color color.diff.meta "default") ;
@@ -89,19 +124,20 @@ gitdiffcoloroff=$(git config --get-color "" "reset") ;
 function diffcore_tool_archive() {
 	local BASE_FILE="${1}"
 	local THIER_FILE="${2}"
-	local MERGE_FILE="${3:-${2}}"
-	echo "diff --git a/${BASE_FILE} b/${THIER_FILE}" | tr -s '/' ;
-	echo "old mode 000000" ;
-	echo "new mode 100644" ;
-	echo -n "index 4b825dc642cb6eb9a060e54bf8d69288fbee4904..";
-	cat <"${BASE_FILE}" | git hash-object -t blob --literally --stdin -- ;
-	diff -pdNU ${GIT_DIFF_TOOL_CONTEXT:-3} --label "a/${BASE_FILE}" --label "b/${BASE_FILE}" "${BASE_FILE}" "${THIER_FILE}" ; wait ;
+	local MERGE_FILE="${3}"
+	local NEW_FILE_INDEX="${4}"
+	echo "diff --git a/${_GIT_DIFF_TOOL_ARCH_PATH}/${MERGE_FILE} b/${_GIT_DIFF_TOOL_ARCH_PATH}/${MERGE_FILE}" | tr -s '/' ;
+	#echo "old mode 000000" ;
+	#echo "new mode ${_GIT_DIFF_TOOL_THIER_MODE}" ;
+	echo -n "index e69de29bb2d1d6434b8b29ae775ad8c2e48c5391.."
+	cat <"${NEW_FILE_INDEX}" | git hash-object -t blob --literally --stdin -- | tr -d \\n
+	echo " ${_GIT_DIFF_TOOL_THIER_MODE}" ;
+	diff -pdNU ${GIT_DIFF_TOOL_CONTEXT:-3} --label "a/${_GIT_DIFF_TOOL_ARCH_PATH}/${MERGE_FILE}" --label "b/${_GIT_DIFF_TOOL_ARCH_PATH}/${MERGE_FILE}" "${BASE_FILE}" "${THIER_FILE}" ; wait ;
 	echo "" ;
 }
 export -f diffcore_tool_archive
 
-#cat <(cat <(tar -tf ${LOCAL} 2>/dev/null ) <(tar -tf ${REMOTE} 2>/dev/null ) | sort -t '/' -u | grep -vE "^.*[/.]+$" | xargs -L1 -I{} -R6 -S${GIT_DIFF_TOOL_FNAMES_BUFFER_LEN} echo "diff -pdNU ${GIT_DIFF_TOOL_CONTEXT:-3} --label '{}' --label '{}' <(tar -xOf "${LOCAL}" '{}' 2>/dev/null ; wait ) <(tar -xOf "${REMOTE}" '{}' 2>/dev/null ; wait ) ; wait ;" ) 2>/dev/null | bash -s ; wait ;
-cat <(cat <(tar -tf ${LOCAL} 2>/dev/null ) <(tar -tf ${REMOTE} 2>/dev/null ) | sort -t '/' -u | grep -vE "^.*[/.]+$" | xargs -L1 -I{} -R6 -S${GIT_DIFF_TOOL_FNAMES_BUFFER_LEN} echo "diffcore_tool_archive <(tar -xOf "${LOCAL}" '{}' 2>/dev/null ; wait ) <(tar -xOf "${REMOTE}" '{}' 2>/dev/null ; wait ) '{}' ; wait ;" ) 2>/dev/null | bash -s ; wait ;
-#cat <(cat <(tar -tf ${LOCAL} 2>/dev/null ) <(tar -tf ${REMOTE} 2>/dev/null ) | sort -t '/' -u | grep -vE "^.*[/.]+$" | xargs -L1 -I{} -R6 -S${GIT_DIFF_TOOL_FNAMES_BUFFER_LEN} echo "diff -pdNU ${GIT_DIFF_TOOL_CONTEXT:-3} --label '{}' --label '{}' <(tar -xOf "${LOCAL}" '{}' 2>/dev/null ; wait ) <(tar -xOf "${REMOTE}" '{}' 2>/dev/null ; wait ) ; wait ;" ) 2>/dev/null | bash -s ; wait ;
+(cat <(cat <(tar -tf ${_GIT_DIFF_TOOL_OUR_PATH} 2>/dev/null ) <(tar -tf ${_GIT_DIFF_TOOL_THIER_PATH} 2>/dev/null ) | sort -t '/' -u | grep -vE "^.*[/.]+$" | xargs -L1 -I{} -R4 -S${GIT_DIFF_TOOL_FNAMES_BUFFER_LEN} echo "diffcore_tool_archive <(tar -xOf "${_GIT_DIFF_TOOL_OUR_PATH}" '{}' 2>/dev/null ; wait ) <(tar -xOf "${_GIT_DIFF_TOOL_THIER_PATH}" '{}' 2>/dev/null ; wait ) '{}' <(tar -xOf "${_GIT_DIFF_TOOL_THIER_PATH}" '{}' 2>/dev/null ; wait ) ; wait ;" ) 2>/dev/null | bash -s ; wait ; ) | sed -Ee 's/^diff\s*(output|--git)?.*/'"${gitdiffmetacolor}"'&/g' | sed -Ee 's/^[\+|-][\+|-][\+|-]\ .*/'"${gitdiffmetacolor}"'&/g' | sed -Ee 's/^(new|old)\s(file\s)?(mode)\s+\d+/'"${gitdiffmetacolor}"'&/g' | sed -Ee 's/^index\s*.+/'"${gitdiffmetacolor}"'&/g' | sed -Ee 's/^@@.*/'"${gitdifffunccolor}"'&/g' | sed -Ee 's/^\+.*/'"${gitdiffnewcolor}"'&/g' | sed -Ee 's/^\ .+/'"${gitdiffcoloroff}"'&/g' | sed -Ee 's/^-.*/'"${gitdiffoldcolor}"'&/g' | sed -Ee 's/$/'${gitdiffcoloroff}'/g'
+
 echo ""
 exit 0 ;
