reorginized

diff --git a/payload/bin/remove_line b/payload/bin/remove_line
--- a/payload/bin/remove_line
+++ b/payload/bin/remove_line
@@ -59,18 +59,38 @@
 #    the amount of five dollars ($5.00). The foregoing limitations will apply
 #    even if the above stated remedy fails of its essential purpose.
 ################################################################################
+# usage ~ remove_line n FILE
+# removes line n from file
 
-# version 20160617
+declare -ir LINE_NUMBER="${1}"
+wait ;
+declare -i BEFORE_LINE_NUMBER=$((${LINE_NUMBER}-1))
+declare -i AFTER_LINE_NUMBER=$((${LINE_NUMBER}+1))
+declare -r THE_FILE="${2}"
 
-# grepCIDR
-
-umask 137
-
-while [[ ($# -gt 1) && (${1:1:1} = '-') ]] ; do
-GREP_ARGS="${GREP_ARGS} ${1}"
-shift
-done
-
-/bin/grep ${GREP_ARGS} -oE "([12]?[0-9]?[0-9]{1}[\.]{1}){3}([12]?[0-9]?[0-9]{1}([/]{1}[1-3]?[0-9]+)?){1}" $@
+if [[ ( -e "${THE_FILE}" ) ]] ; then
+	if [[ ( -r "${THE_FILE}" ) ]] ; then
+		if [[ ( -w "${THE_FILE}" ) ]] ; then
+			if [[ ( ${BEFORE_LINE_NUMBER} -gt 0 ) ]] ; then
+				head -n ${BEFORE_LINE_NUMBER} ${THE_FILE} || exit 1 ;
+				wait ;
+			fi
+			# line is removed
+			if [[ ( $(wc -l ${THE_FILE} | grep -m 1 -o "[0-9]+" | head -n 1) -lt ${AFTER_LINE_NUMBER} ) ]] ; then
+				tail -n +${AFTER_LINE_NUMBER} ${THE_FILE} || exit 1 ;
+			fi
+			wait ;
+		else
+			echo "ERROR: ${THE_FILE} is not writeable." 1>&2 ; wait ;
+			exit 4;
+		fi
+	else
+		echo "ERROR: ${THE_FILE} can not be read." 1>&2 ; wait ;
+		exit 3;
+	fi
+else
+	echo "ERROR: ${THE_FILE} can not be found." 1>&2 ; wait ;
+	exit 2;
+fi
 
 exit 0 ;
diff --git a/payload/bin/sud b/payload/bin/sud
--- a/payload/bin/sud
+++ b/payload/bin/sud
@@ -64,16 +64,8 @@ THE_URL="${1}"
 
 umask 137
 
-TEMP_FILE_CACHE="/var/tmp/safe_web_path_site"
+TEMP_FILE_CACHE="/var/tmp/safe_web_path_site_${GID:-x}_${RANDOM}.data"
 DEST_FILE_PATH="${2}"
-
-#if [[ ( $(echo "${SITE_NAME}" | grep -ocE "[[:punct:]]{1}$" | grep -oE -m 1 "[0-9]+" ) -ge 1 ) ]] ; then
-#                declare -i SOME_SITE_LENGTH=$(echo -n "${1}" | wc -c | grep -oE -m 1 "[0-9]+")
-#                wait ;
-#                SOME_SITE_LENGTH=$((${SOME_SITE_LENGTH}-1))
-#                wait ;
-#                SITE_NAME=${1:0:$SOME_SITE_LENGTH}
-#fi
 
 function cleanup() {
 if [[ ( -e ${TEMP_FILE_CACHE} ) ]] ; then rm -f ${TEMP_FILE_CACHE} 2>/dev/null ; wait ; fi ;
@@ -89,7 +81,7 @@ trap 'cleanup ; wait ; exit 1 ;' SIGTERM ;
 
 HEADER_HOST=$(echo "${THE_URL}" | grepdns -m 1 )
 
-HEADER_TYPE=$(\curl --user-agent "SUD/1.1" --url ${THE_URL} --retry 1 --show-error --max-redirs 0 --header "Host: ${THE_URL}" --header "Dnt: 1" --header "Connection: close" -j -L --ipv4 -s -S -I | grep -oE "[T]{1}[y]{1}[p]{1}[e]{1}[:]{1}[[:space:]]+[[:print:]]+")
+HEADER_TYPE=$(\curl --user-agent "SUD/1.1" --url ${THE_URL} --retry 1 --show-error --max-redirs 0 --header "Host: ${HEADER_HOST}" --header "Dnt: 1" --header "Connection: close" -j -L --ipv4 -s -S -I | grep -oE "[T]{1}[y]{1}[p]{1}[e]{1}[:]{1}[[:space:]]+[[:print:]]+")
 HEADER_TYPE="${HEADER_TYPE:6}"
 echo "Host: ${HEADER_HOST}"
 echo "Accept: ${HEADER_TYPE}"
@@ -101,10 +93,10 @@ echo "# FAILED" ;
 exit 0;
 else
 clamscan --no-summary -i -r --detect-pua=no --remove=yes --tempdir=/var/tmp "${TEMP_FILE_CACHE}"
-if [[ ( $? -gt 1 ) ]] ; then exit 1 ; fi ;
+if [[ ( $? -gt 1 ) ]] ; then echo "### UNSAFE ###" && cleanup ; wait ; exit 1 ; fi ;
 clamscan --no-summary -r --detect-pua=yes --remove=no --tempdir=/var/tmp "${TEMP_FILE_CACHE}"
 fi ;
 
-mv -f "${TEMP_FILE_CACHE}" "${DEST_FILE_PATH}"
+mv -f "${TEMP_FILE_CACHE}" "${DEST_FILE_PATH}" ; sync ; wait ;
 
 exit 0;
